export const country1 = [
  { name: "Argentina", isCountry: true },
  { name: "Celina Hilbert", isCountry: false },
  { name: "Australia", isCountry: true },
  { name: "Alena Smith Interior Design", isCountry: false },
  { name: "Andrew Sloan", isCountry: false },
  { name: "Andrew Vaughan", isCountry: false },
  { name: "Andy Marks", isCountry: false },
  { name: "Arielle Breit", isCountry: false },
  { name: "Art Disrupt", isCountry: false },
  { name: "Austin Smidt", isCountry: false },
  { name: "AUTHENTIC DESIGN ALLIANCE (ADA)", isCountry: false },
  { name: "Ben Rennie", isCountry: false },
  { name: "BETTER FUTURE", isCountry: false },
  { name: "Bohdan Dorniak & Co Pty Ltd - PROSPECT, SA", isCountry: false },
  { name: "Brand & Communications at Edge Impact", isCountry: false },
  { name: "Breathe Architecture", isCountry: false },
  { name: "BWD Strategic", isCountry: false },
  { name: "Cameron Tonkinwise", isCountry: false },
  { name: "Carbon Creative", isCountry: false },
  { name: "Carolyn King", isCountry: false },
  { name: "Celine Waters", isCountry: false },
  { name: "Charlotte Adams", isCountry: false },
  { name: "Design by Nature", isCountry: false },
  { name: "Design Consigned", isCountry: false },
  { name: "Diadem", isCountry: false },
  { name: "Dr Michelle Douglas FRSA", isCountry: false },
  { name: "eco creative agency", isCountry: false },
  { name: "Ethos Digital Agency", isCountry: false },
  { name: "Finbar", isCountry: false },
  { name: "Founded by Design Pty Ltd", isCountry: false },
  { name: "Frost*", isCountry: false },
  { name: "Gabriella Wilson", isCountry: false },
  { name: "Genius Agency", isCountry: false },
  { name: "Geoff Isaac", isCountry: false },
  { name: "Glen Barry", isCountry: false },
  { name: "Gloria Quiroga", isCountry: false },
  { name: "Good 4 Business", isCountry: false },
  { name: "Good Design Australia", isCountry: false },
  { name: "Goodness", isCountry: false },
  { name: "Goodsports", isCountry: false },
  { name: "Hammond Studio", isCountry: false },
  { name: "Harry Steer", isCountry: false },
  { name: "Heidi Romano", isCountry: false },
  { name: "Holonic", isCountry: false },
  { name: "Hortenzia", isCountry: false },
  { name: "James Hodgson Design", isCountry: false },
  { name: "Jas Soh", isCountry: false },
  { name: "Jeremy Yuille", isCountry: false },
  { name: "Jo Li Tay", isCountry: false },
  { name: "John Young", isCountry: false },
  { name: "Josh Riesel", isCountry: false },
  { name: "Karina Clarke", isCountry: false },
  { name: "Katapult Design", isCountry: false },
  { name: "Kirby C", isCountry: false },
  { name: "Koskela", isCountry: false },
  { name: "Leigh Phillips-Brown", isCountry: false },
  { name: "Leigh-Anne Hepburn", isCountry: false },
  { name: "Leyla Acaroglu", isCountry: false },
  { name: "Liane Rossler", isCountry: false },
  { name: "LPB Designs and Interiors", isCountry: false },
  { name: "Madeline Johnston", isCountry: false },
  { name: "Make Tomorrow™", isCountry: false },
  { name: "Marnie Hawson", isCountry: false },
  { name: "Martin Tomitsch", isCountry: false },
  { name: "MEK Studio", isCountry: false },
  { name: "Mirella Arapian", isCountry: false },
  { name: "Moffitt.Moffitt.", isCountry: false },
  { name: "Motherbird", isCountry: false },
  { name: "Nacara Studio", isCountry: false },
  { name: "Nila Rezaei", isCountry: false },
  { name: "Particle Design Studio", isCountry: false },
  { name: "Philip Ely PhD", isCountry: false },
  { name: "philo & co", isCountry: false },
  { name: "Planitree", isCountry: false },
  { name: "Reny Studio", isCountry: false },
  { name: "Reny®", isCountry: false },
  { name: "Ricardo Sosa", isCountry: false },
  { name: "RK Collective", isCountry: false },
{ name: "RMIT University", isCountry: false },
{ name: "Samuel Yu", isCountry: false },
{ name: "Seek & Design", isCountry: false },
{ name: "Snug House", isCountry: false },
{ name: "Society for Responsible Design Inc.", isCountry: false },
{ name: "Sponge", isCountry: false },
{ name: "Stephanie Mulder", isCountry: false },
{ name: "Steve Baty", isCountry: false },
{ name: "STUDIO PERISCOPE", isCountry: false },
{ name: "Studio Regina", isCountry: false },
{ name: "studiospillane", isCountry: false },
{ name: "Tanisha Maria Naik", isCountry: false },
{ name: "The Design Thinkers", isCountry: false },
{ name: "UNEND", isCountry: false },
{ name: "United Studio", isCountry: false },
{ name: "vert design", isCountry: false },
{ name: "Wendy Fountain", isCountry: false },
{ name: "X+O", isCountry: false },
{ name: "Ys", isCountry: false },
{ name: "Zero Co pty Ltd", isCountry: false },
{ name: "Austria", isCountry: true },
{ name: "Luain", isCountry: false },
{ name: "Bangladesh", isCountry: true },
{ name: "Rifat Anik", isCountry: false },
{ name: "Belgium", isCountry: true },
{ name: "Air", isCountry: false },
{ name: "Blue Kameleon SRL", isCountry: false },
{ name: "Core Branding", isCountry: false },
{ name: "Futurewave", isCountry: false },
{ name: "HIER", isCountry: false },
{ name: "Orb", isCountry: false },
{ name: "Brazil", isCountry: true },
{ name: "Adriana Tamashiro", isCountry: false },
{ name: "RMIT University", isCountry: false },
{ name: "Samuel Yu", isCountry: false },
{ name: "Seek & Design", isCountry: false },
{ name: "Snug House", isCountry: false },
{ name: "Society for Responsible Design Inc.", isCountry: false },
{ name: "Sponge", isCountry: false },
{ name: "Stephanie Mulder", isCountry: false },
{ name: "Steve Baty", isCountry: false },
{ name: "STUDIO PERISCOPE", isCountry: false },
{ name: "Studio Regina", isCountry: false },
{ name: "studiospillane", isCountry: false },
{ name: "Tanisha Maria Naik", isCountry: false },
{ name: "The Design Thinkers", isCountry: false },
{ name: "UNEND", isCountry: false },
{ name: "United Studio", isCountry: false },
{ name: "vert design", isCountry: false },
{ name: "Wendy Fountain", isCountry: false },
{ name: "X+O", isCountry: false },
{ name: "Ys", isCountry: false },
{ name: "Zero Co pty Ltd", isCountry: false },
{ name: "Austria", isCountry: true },
{ name: "Luain", isCountry: false },
{ name: "Bangladesh", isCountry: true },
{ name: "Rifat Anik", isCountry: false },
{ name: "Belgium", isCountry: true },
{ name: "Air", isCountry: false },
{ name: "Blue Kameleon SRL", isCountry: false },
{ name: "Core Branding", isCountry: false },
{ name: "Futurewave", isCountry: false },
{ name: "HIER", isCountry: false },
{ name: "Orb", isCountry: false },
{ name: "Brazil", isCountry: true },
{ name: "Adriana Tamashiro", isCountry: false },
{ name: "Adriana Tamashiro", isCountry: false },
{ name: "Agatha Martins", isCountry: false },
{ name: "Alexander Ângelo Guazzelli", isCountry: false },
{ name: "Alexandre de Oliveira Lot", isCountry: false },
{ name: "Amanda Lima Neves Scorsolini", isCountry: false },
{ name: "Ana Luísa Canto", isCountry: false },
{ name: "Ana Paula Batista", isCountry: false },
{ name: "Audrey Italo Melo", isCountry: false },
{ name: "BRQ Digital Solutions", isCountry: false },
{ name: "Bruna Cerasi", isCountry: false },
{ name: "Bruna Luiza Schwendler", isCountry: false },
{ name: "Bruna Mattos", isCountry: false },
{ name: "Brunna Moura", isCountry: false },
{ name: "BRUNO FREIRE PERRONE", isCountry: false },
{ name: "Cacto Publicidade", isCountry: false },
{ name: "Camila Calegari Marques", isCountry: false },
{ name: "Camila de Almeida Santos", isCountry: false },
{ name: "Camila Lozeckyi", isCountry: false },
{ name: "Carlos Filipe Alves Lima", isCountry: false },
{ name: "Carlos Ignacio Hernández Tellez", isCountry: false },
{ name: "Carol Hoffmann", isCountry: false },
{ name: "CECILIA PACHECO", isCountry: false },
{ name: "Chelles & Hayashi Design", isCountry: false },
{ name: "christian ullmann", isCountry: false },
{ name: "Claudia Mardegan", isCountry: false },
{ name: "Claudio Pelizari", isCountry: false },
{ name: "Danton Gravina", isCountry: false },
{ name: "Denilson Silva", isCountry: false },
{ name: "Denise Oliveira Martins", isCountry: false },
{ name: "Design Docol at Docol Sanitaryware", isCountry: false },
{ name: "Design Team at WIS Learn", isCountry: false },
{ name: "DI", isCountry: false },
{ name: "Diego Nunes", isCountry: false },
{ name: "Diogo Lucato", isCountry: false },
{ name: "DPO Saudável", isCountry: false },
{ name: "Echos", isCountry: false },
{ name: "Eduardo Maia", isCountry: false },
{ name: "Eliane Quadro", isCountry: false },
{ name: "Empathy Company", isCountry: false },
{ name: "Estúdio Atômico", isCountry: false },
{ name: "Estúdio Guto Requena", isCountry: false },
{ name: "Estudio Marte", isCountry: false },
{ name: "Fares Saba Jr", isCountry: false },
{ name: "Fernanda", isCountry: false },
{ name: "Fernanda Fidelis", isCountry: false },
{ name: "Fernanda Romera", isCountry: false },
{ name: "Fluyd", isCountry: false },
{ name: "Francisco Albuquerque", isCountry: false },
{ name: "GABRIEL ESTEVES DE OLIVEIRA LEITAO", isCountry: false },
{ name: "George Rutherford", isCountry: false },
{ name: "GIOVANA LORENA FAZIONI", isCountry: false },
{ name: "Green Mandarin", isCountry: false },
{ name: "Green Mandarin", isCountry: false },
{ name: "Greg Lopes", isCountry: false },
{ name: "IMK Arquitetura e Engenharia", isCountry: false },
{ name: "Jaakko Tammela", isCountry: false },
{ name: "Jenifer Rodrigues", isCountry: false },
{ name: "Juan Solís Gundín", isCountry: false },
{ name: "JULIA RESENDE", isCountry: false },
{ name: "Júlia Timponi", isCountry: false },
{ name: "JULIANA SIDSAMER", isCountry: false },
{ name: "Julianny aidel rafea", isCountry: false },
{ name: "Junior Magalhães", isCountry: false },
{ name: "KAREN TIE KAWAKAMI", isCountry: false },
{ name: "Karla Scherer", isCountry: false },
{ name: "Larissa Nunes", isCountry: false },
{ name: "Leo Eyer", isCountry: false },
{ name: "Leonardo Lins", isCountry: false },
{ name: "Lincoln Seragini", isCountry: false },
{ name: "Lincoln Shiguio", isCountry: false },
{ name: "Lincoln Shiguio", isCountry: false },
{ name: "Luciana Shirakawa", isCountry: false },
{ name: "LUIS FERNANDO OSCAR COSTA", isCountry: false },
{ name: "Maialu Ferlauto", isCountry: false },
{ name: "Marcelo F. Pereira Junior", isCountry: false },
{ name: "Marcelo Sales", isCountry: false },
{ name: "Marcon Zanin", isCountry: false },
{ name: "Marcos Vinícius Machado de Oliveira", isCountry: false },
{ name: "Maria de Fátima Gullino Frazão", isCountry: false },
{ name: "Maria Elisa Zaia", isCountry: false },
{ name: "Mariana Fonseca de Souza", isCountry: false },
{ name: "Mariana Pereira Weber", isCountry: false },
{ name: "Mateus Bull Furlan", isCountry: false },
{ name: "Mayra Sasso", isCountry: false },
{ name: "Nathalia Petta", isCountry: false },
{ name: "paaassos design studio", isCountry: false },
{ name: "Pamela Basilio", isCountry: false },
{ name: "Patricia Watson", isCountry: false },
{ name: "Paula Cristiani Takahashi", isCountry: false },
{ name: "Paulo Peres", isCountry: false },
{ name: "Paulo Santos", isCountry: false },
{ name: "Pedro Gomes", isCountry: false },
{ name: "Pedro Martins e Souza", isCountry: false },
{ name: "Pedro Naif", isCountry: false },
{ name: "Pedro Pazitto", isCountry: false },
{ name: "PPTzeiros", isCountry: false },
{ name: "Raissa Esther", isCountry: false },
{ name: "Raquel Lima", isCountry: false },
{ name: "RedBandana Branding and Design", isCountry: false },
{ name: "Rei Campos Inovação em Serviços", isCountry: false },
{ name: "Renan Benvenuti", isCountry: false },
{ name: "Renan Migliorini", isCountry: false },
{ name: "Renata matos", isCountry: false },
{ name: "Renato Winnig", isCountry: false },
{ name: "Robson Zumkeller", isCountry: false },
{ name: "Robson Zumkeller", isCountry: false },
{ name: "RODRIGO ANTONIO QUEIROZ COSTA", isCountry: false },
{ name: "Rodrigo Peixoto", isCountry: false },
{ name: "Sandra Ribeiro Cameira", isCountry: false },
{ name: "Simbïo Design", isCountry: false },
{ name: "Studio Allure", isCountry: false },
{ name: "tellus", isCountry: false },
{ name: "Thayane", isCountry: false },
{ name: "Thiago Barreto", isCountry: false },
{ name: "Thiago Vieira Marques", isCountry: false },
{ name: "Thoz", isCountry: false },
{ name: "tiago taveira", isCountry: false },
{ name: "Tudo é Acessibilidade", isCountry: false },
{ name: "UERJ", isCountry: false },
{ name: "Vagner Trevisan", isCountry: false },
{ name: "Vanessa Silva", isCountry: false },
{ name: "Victor Maluhy", isCountry: false },
{ name: "Victor Mascarenhas", isCountry: false },
{ name: "VIRGINIA CORNELSEN", isCountry: false },
{ name: "Visorama", isCountry: false },
{ name: "Wagner Lúcio", isCountry: false },
{ name: "weme", isCountry: false },
{ name: "Bulgaria", isCountry: true },
{ name: "Ivelina Dimitrova", isCountry: false },
{ name: "Canada", isCountry: true },
{ name: "Ardeshir Amini", isCountry: false },
{ name: "Cense Ltd.", isCountry: false },
{ name: "Eliane Bowden", isCountry: false },
{ name: "Fletcher Scott Studio Inc.", isCountry: false },
{ name: "Meghan Hellstern", isCountry: false },
{ name: "PiTCH PR", isCountry: false },
{ name: "PiTCH PR", isCountry: false },
{ name: "Project 42", isCountry: false },
{ name: "Ryan Mayer", isCountry: false },
{ name: "SUPERFORT Creative Agency", isCountry: false },
{ name: "China", isCountry: true },
{ name: "Campaign Design", isCountry: false },
{ name: "Orange Creatives", isCountry: false },
{ name: "Platform88", isCountry: false },
{ name: "Colombia", isCountry: true },
{ name: "Coombo", isCountry: false },
{ name: "Leticia", isCountry: false },
{ name: "Croatia", isCountry: true },
{ name: "Creek and Pine", isCountry: false },
{ name: "Protagonist agencija", isCountry: false },
{ name: "Czechia", isCountry: true },
{ name: "Sandra", isCountry: false },
{ name: "Denmark", isCountry: true },
{ name: "BineJoMo Studio", isCountry: false },
{ name: "CurledDesign", isCountry: false },
{ name: "Louise Ryberg", isCountry: false },
{ name: "Make Material ApS", isCountry: false },
{ name: "Sabin Bors", isCountry: false },
{ name: "TAWS", isCountry: false },
{ name: "Finland", isCountry: true },
{ name: "Diseño y diáspora podcast", isCountry: false },
{ name: "France", isCountry: true },
{ name: "Archipel Kyosei at Archipel Kyosei", isCountry: false },
{ name: "Atelier de recherche temporelle at a-r-t", isCountry: false },
{ name: "Campus des Métiers et des Qualifications Image et Design Hauts de France", isCountry: false },
{ name: "Christopher Bellamy", isCountry: false },
{ name: "CY school of design", isCountry: false },
{ name: "Kristen", isCountry: false },
{ name: "LAB'S 214", isCountry: false },
{ name: "madd-bordeaux", isCountry: false },
{ name: "OUTERCRAFT", isCountry: false },
{ name: "Valérie Tortolero", isCountry: false },
{ name: "Germany", isCountry: true },
{ name: "Amarjith Sreekumar", isCountry: false },
{ name: "andreas popp", isCountry: false },
{ name: "Ashley Scarborough", isCountry: false },
{ name: "Bendcircular", isCountry: false },
{ name: "Bureau Braun", isCountry: false },
{ name: "Gloria Ciceri", isCountry: false },
{ name: "hoch E", isCountry: false },
{ name: "JDS", isCountry: false },
{ name: "Jessica Metro", isCountry: false },
{ name: "Joshua Stehr", isCountry: false },
{ name: "Katharina Winter", isCountry: false },
{ name: "Matt Granger", isCountry: false },
{ name: "NEW STANDARD.STUDIO", isCountry: false },
{ name: "Paolo de Jesus", isCountry: false },
{ name: "Philip Hugle", isCountry: false },
{ name: "Plan C. Studio", isCountry: false },
{ name: "Schober+Richter", isCountry: false },
{ name: "STUDIO CDW", isCountry: false },
{ name: "The Design & Emotion Lab", isCountry: false },
{ name: "Thorsten Jonas", isCountry: false },
{ name: "Tillmann Schrempf", isCountry: false },
{ name: "White Lime", isCountry: false },
{ name: "Gibraltar", isCountry: true },
{ name: "Entain", isCountry: false },
{ name: "Guatemala", isCountry: true },
{ name: "Fabrizio Constanza", isCountry: false },
{ name: "India", isCountry: true },
{ name: "A BLUNT STORY", isCountry: false },
{ name: "Aboa Hasa Foundation", isCountry: false },
{ name: "Dinu Prasanna Kennedy", isCountry: false },
{ name: "DxE Inc.", isCountry: false },
{ name: "LOCAL", isCountry: false },
{ name: "Minto Joy", isCountry: false },
{ name: "Sai Challa", isCountry: false },
{ name: "Shona Sinha", isCountry: false },
{ name: "Shreya Salian", isCountry: false },
{ name: "Indonesia", isCountry: true },
{ name: "Andini Putri Pramudya Wardani", isCountry: false },
{ name: "Nice To Meet You Studio", isCountry: false },
{ name: "Skemasocial", isCountry: false },
{ name: "Ireland", isCountry: true },
{ name: "A Worthy Cause", isCountry: false },
{ name: "Aaron O'Neill", isCountry: false },
{ name: "Abigail Smith", isCountry: false },
{ name: "Alanna Campbell", isCountry: false },
{ name: "Alessandra Ravida", isCountry: false },
{ name: "Alkamee", isCountry: false },
{ name: "Alphabet Soup", isCountry: false },
{ name: "Anastasiia Chorna", isCountry: false },
{ name: "Andrew Anderson", isCountry: false },
{ name: "Babelfís", isCountry: false },
{ name: "BIEN", isCountry: false },
{ name: "Billion Studio", isCountry: false },
{ name: "Bradley: The Brand Agency", isCountry: false },
{ name: "Bren Byrne", isCountry: false },
{ name: "Brian Morgan", isCountry: false },
{ name: "Caio", isCountry: false },
{ name: "Cairenn", isCountry: false },
{ name: "Capulet and montague", isCountry: false },
{ name: "Carlos Garcia", isCountry: false },
{ name: "Chapter", isCountry: false },
{ name: "Chart Design Studio", isCountry: false },
{ name: "Ciara Broujos Design", isCountry: false },
{ name: "Ciara Layden", isCountry: false },
{ name: "Ciara Wade", isCountry: false },
{ name: "Circular Design Institute", isCountry: false },
{ name: "Claire Dillon", isCountry: false },
{ name: "Claire Dillon", isCountry: false },
{ name: "Clare Lynch", isCountry: false },
{ name: "Claudia Fini", isCountry: false },
{ name: "Claudine Curran", isCountry: false },
{ name: "Claudine Leonard Design", isCountry: false },
{ name: "Clever Ghost at Clever Ghost", isCountry: false },
{ name: "Cliodhna Ryan", isCountry: false },
{ name: "Conor Flood", isCountry: false },
{ name: "Conor Nolan", isCountry: false },
{ name: "consider it design", isCountry: false },
{ name: "Context Studio", isCountry: false },
{ name: "CREW", isCountry: false },
{ name: "Cróna Connolly", isCountry: false },
{ name: "CUBE Design", isCountry: false },
{ name: "Damian Sherlock", isCountry: false },
{ name: "Dan Eames", isCountry: false },
{ name: "Danielle Deveney", isCountry: false },
{ name: "Danielle Townsend", isCountry: false },
{ name: "David Wall", isCountry: false },
{ name: "Déanta Studio", isCountry: false },
{ name: "Declan Behan", isCountry: false },
{ name: "Design for Sustinability & Circular Economies Certificate at Limerick School of Art & Design , TUS", isCountry: false },
{ name: "Design Notions", isCountry: false },
{ name: "Design Partners", isCountry: false },
{ name: "Design Studio at Maverick Communications", isCountry: false },
{ name: "Detail Design Studio", isCountry: false },
{ name: "Digital Factory at ESB", isCountry: false },
{ name: "Disco Milk", isCountry: false },
{ name: "Duanna Taylor Rooney", isCountry: false },
{ name: "Each&Other", isCountry: false },
{ name: "Éilís Murphy", isCountry: false },
{ name: "Éimear O'Sullivan", isCountry: false },
{ name: "Emberlight", isCountry: false },
{ name: "Emi Daly", isCountry: false },
{ name: "Emma Nolan", isCountry: false },
{ name: "EPIC Interpretive Design", isCountry: false },
{ name: "Fly Bird Design", isCountry: false },
{ name: "FUSE Graphic Design Ltd", isCountry: false },
{ name: "Global Creative at Johnson Controls", isCountry: false },
{ name: "Good As Gold", isCountry: false },
{ name: "Grace", isCountry: false },
{ name: "Graphic Design [+] at IADT", isCountry: false },
{ name: "Graphic Design Communication at LSAD at TUS", isCountry: false },
{ name: "Griffith College Design", isCountry: false },
{ name: "Image Now", isCountry: false },
{ name: "Image Now", isCountry: false },
{ name: "Imagine Lab", isCountry: false },
{ name: "Iman", isCountry: false },
{ name: "Ingrid Smyth", isCountry: false },
{ name: "Institute of Designers Ireland", isCountry: false },
{ name: "Isabel Staunton", isCountry: false },
{ name: "Jamie Whelan", isCountry: false },
{ name: "Jeffers & Sons", isCountry: false },
{ name: "Joan Ellison", isCountry: false },
{ name: "Johanna Legnar", isCountry: false },
{ name: "John Connolly", isCountry: false },
{ name: "John Connolly", isCountry: false },
{ name: "John O'Brien", isCountry: false },
{ name: "Jonny Willis", isCountry: false },
{ name: "Kacper Jaroszynski", isCountry: false },
{ name: "Kalil Dunne", isCountry: false },
{ name: "Kanupriya Jamwal", isCountry: false },
{ name: "Karl Smyth", isCountry: false },
{ name: "Karl Toomey", isCountry: false },
{ name: "Kate Brangan", isCountry: false },
{ name: "Katy May O’Sullivan", isCountry: false },
{ name: "Kelly Hood", isCountry: false },
{ name: "Lands", isCountry: false },
{ name: "Lara Hanlon", isCountry: false },
{ name: "Lisa Zimmermann", isCountry: false },
{ name: "Lucy Bowen", isCountry: false },
{ name: "Luke McLaughlin", isCountry: false },
{ name: "M-CO", isCountry: false },
{ name: "MAKER", isCountry: false },
{ name: "Mallory Frye", isCountry: false },
{ name: "Marguerite", isCountry: false },
{ name: "Marie Gordon", isCountry: false },
{ name: "Marino Software", isCountry: false },
{ name: "Meghan Clapham", isCountry: false },
{ name: "Melvin Jayson C. Ogbalu", isCountry: false },
{ name: "Michelle Urban", isCountry: false },
{ name: "Mike Mahon", isCountry: false },
{ name: "New Graphic", isCountry: false },
{ name: "Neworld", isCountry: false },
{ name: "Oisin MacManus", isCountry: false },
{ name: "Olivia humphreys", isCountry: false },
{ name: "On The Dot", isCountry: false },
{ name: "Open Studio", isCountry: false },
{ name: "Outburst Design", isCountry: false },
{ name: "Path", isCountry: false },
{ name: "Patrick Feeney", isCountry: false },
{ name: "Paula McEntee", isCountry: false },
{ name: "Penhouse Design", isCountry: false },
{ name: "Peter Sheehan Studio", isCountry: false },
{ name: "Piquant", isCountry: false },
{ name: "Pixelpod", isCountry: false },
{ name: "POND Studios", isCountry: false },
{ name: "Portion Collaborative", isCountry: false },
{ name: "Post Studio", isCountry: false },
{ name: "Prof Dip and MA Service Design team at National College of Art and Design", isCountry: false },
{ name: "Public Design Lab at IADT", isCountry: false },
{ name: "Purple Peach", isCountry: false },
{ name: "Raluca Turcanasu", isCountry: false },
{ name: "Rebecca Wright", isCountry: false },
{ name: "Rebecca Wright", isCountry: false },
{ name: "Red Dog", isCountry: false },
{ name: "Richard Whitty", isCountry: false },
{ name: "RIFORMA collective", isCountry: false },
{ name: "Róisín Jordan", isCountry: false },
{ name: "Ross Harrington", isCountry: false },
{ name: "Ruairí Crawley", isCountry: false },
{ name: "Sadhbh Murphy", isCountry: false },
{ name: "Sasha Sykes Studio", isCountry: false },
{ name: "Self employed - Nichola Wolfe.com", isCountry: false },
{ name: "Serena Chille", isCountry: false },
{ name: "Shane Casey", isCountry: false },
{ name: "Sharon Maxwell", isCountry: false },
{ name: "Signal Type Founddry", isCountry: false },
{ name: "SLMD", isCountry: false },
{ name: "So Studio", isCountry: false },
{ name: "Sorcha Fitzgerald", isCountry: false },
{ name: "Stefan Paz", isCountry: false },
{ name: "Studio Kosmos", isCountry: false },
{ name: "Studio Saol", isCountry: false },
{ name: "studiomir", isCountry: false },
{ name: "Superfolk", isCountry: false },
{ name: "Susan Carberry", isCountry: false },
{ name: "Sweet! Graphic Design", isCountry: false },
{ name: "The Factory", isCountry: false },
{ name: "The FACTORY", isCountry: false },
{ name: "The Public House", isCountry: false },
{ name: "THINKHOUSE", isCountry: false },
{ name: "Together We Create", isCountry: false },
{ name: "Treetop Studio", isCountry: false },
{ name: "University of Limerick", isCountry: false },
{ name: "Unthink", isCountry: false },
{ name: "Wes Trumble Design", isCountry: false },
{ name: "Wilson Creative", isCountry: false },
{ name: "Wove", isCountry: false },
{ name: "Isle of Man", isCountry: true },
{ name: "Studio Cooper", isCountry: false },
{ name: "Italy", isCountry: true },
{ name: "acy", isCountry: false },
{ name: "chiara de angelis", isCountry: false },
{ name: "Elisabeth Graf", isCountry: false },
{ name: "Gianluca Menini", isCountry: false },
{ name: "Kāvya Raman", isCountry: false },
{ name: "Michael Brenner", isCountry: false },
{ name: "Ox design studio", isCountry: false },
{ name: "Simona Audino", isCountry: false },
{ name: "Japan", isCountry: true },
{ name: "Asuka Kondo", isCountry: false },
{ name: "Latvia", isCountry: true },
{ name: "Drinking Water", isCountry: false },
{ name: "Ēvija Kraukle", isCountry: false },
{ name: "Lebanon", isCountry: true },
{ name: "Designerwork", isCountry: false },
{ name: "Lithuania", isCountry: true },
{ name: "Viktorija", isCountry: false },
{ name: "Luxembourg", isCountry: true },
{ name: "Art Square Lab SARL-S SIS", isCountry: false },
{ name: "Malta", isCountry: true },
{ name: "Abigail Farrugia", isCountry: false },
{ name: "Mexico", isCountry: true },
{ name: "Alex Quinto", isCountry: false },
{ name: "Gustavo González D’Asseo", isCountry: false },
{ name: "HD*", isCountry: false },
{ name: "Monserrat Aranzazú Moreno García", isCountry: false },
{ name: "Narativ Design", isCountry: false },
{ name: "Morocco", isCountry: true },
{ name: "evergreen pixel agency", isCountry: false },
{ name: "Netherlands", isCountry: true },
{ name: "Archites", isCountry: false },
{ name: "Circu Leren", isCountry: false },
{ name: "Creative Mules", isCountry: false },
{ name: "Danni Swalef", isCountry: false },
{ name: "Edwin van Maanen", isCountry: false },
{ name: "Gabriela Bassa", isCountry: false },
{ name: "Leon van Hoof", isCountry: false },
{ name: "Nadine", isCountry: false },
{ name: "Rg/B", isCountry: false },
{ name: "Rogier Barendregt", isCountry: false },
{ name: "Rogier Barendregt", isCountry: false },
{ name: "Sustainable Digital Design", isCountry: false },
{ name: "Wessel Jansen", isCountry: false },
{ name: "New Zealand", isCountry: true },
{ name: "Andrew Roberts", isCountry: false },
{ name: "Clark Bardsley Design", isCountry: false },
{ name: "Dani Bond", isCountry: false },
{ name: "Nicaragua", isCountry: true },
{ name: "Bernardo van de Schepop", isCountry: false },
{ name: "Nigeria", isCountry: true },
{ name: "Nuel Wogundu", isCountry: false },
{ name: "Ridwan Awujoola", isCountry: false },
{ name: "Norway", isCountry: true },
{ name: "Petchy", isCountry: false },
{ name: "Respira", isCountry: false },
{ name: "Pakistan", isCountry: true },
{ name: "Ali Murtaza", isCountry: false },
{ name: "Syed Faizan Raza", isCountry: false },
{ name: "Philippines", isCountry: true },
{ name: "Darwin Antipolo", isCountry: false },
{ name: "Jesi Sumeg-ang", isCountry: false },
{ name: "Mathijs Sterrenburg", isCountry: false },
{ name: "TAYO Change Agency: House of Culture & Creativity", isCountry: false },
{ name: "Poland", isCountry: true },
{ name: "Ergodesign", isCountry: false },
{ name: "Weronika Wojnarowicz", isCountry: false },
{ name: "Portugal", isCountry: true },
{ name: "Afonso Miguel Tomaz Assis dos Santos Januário", isCountry: false },
{ name: "Bernd Herbert", isCountry: false },
{ name: "Carolina Borges Sacoto", isCountry: false },
{ name: "Crystal Campbell", isCountry: false },
{ name: "Daniela Veloso", isCountry: false },
{ name: "FERNANDO MENDES", isCountry: false },
{ name: "Graeme McCree", isCountry: false },
{ name: "Joana Casaca Lemos LDA", isCountry: false },
{ name: "Pedro Miguel Gago Pereira", isCountry: false },
{ name: "Rossouw Oosthuizen", isCountry: false },
{ name: "Tassiane Castro", isCountry: false },
{ name: "Romania", isCountry: true },
{ name: "Alex Ardelean", isCountry: false },
{ name: "Madalina Hamciuc", isCountry: false },
{ name: "Singapore", isCountry: true },
{ name: "Audrey Yang", isCountry: false },
{ name: "Dignité Brands", isCountry: false },
{ name: "Slovenia", isCountry: true },
{ name: "Petra Černe Oven", isCountry: false },
{ name: "Sito", isCountry: false },
{ name: "South Africa", isCountry: true },
{ name: "Duncan Stevens", isCountry: false },
{ name: "the earth is round", isCountry: false },
{ name: "Spain", isCountry: true },
{ name: "Alberto Carnero", isCountry: false },
{ name: "Banda", isCountry: false },
{ name: "Blackbot", isCountry: false },
{ name: "Catalina Estrada", isCountry: false },
{ name: "David O'Mahony", isCountry: false },
{ name: "Design Thinkers Group Spain", isCountry: false },
{ name: "Diego González", isCountry: false },
{ name: "Edu Gonzalez", isCountry: false },
{ name: "Elena Martinez", isCountry: false },
{ name: "estudio flúor", isCountry: false },
{ name: "Estudio República", isCountry: false },
{ name: "Federico Víllora", isCountry: false },
{ name: "Folks", isCountry: false },
{ name: "Folks Brands", isCountry: false },
{ name: "Gerard", isCountry: false },
{ name: "Glenn Goodwin", isCountry: false },
{ name: "holon coop", isCountry: false },
{ name: "Jesús Gallent", isCountry: false },
{ name: "Laura Fernández", isCountry: false },
{ name: "Lucinda Morrissey", isCountry: false },
{ name: "María Jesús Bonafonte", isCountry: false },
{ name: "Mean Creative", isCountry: false },
{ name: "Monnou", isCountry: false },
{ name: "MOS. More on Simplicity", isCountry: false },
{ name: "MUAK STUDIO", isCountry: false },
{ name: "Nixae", isCountry: false },
{ name: "PATRICIA SALCEDO", isCountry: false },
{ name: "The Hatch Studio", isCountry: false },
{ name: "Sweden", isCountry: true },
{ name: "Antrop", isCountry: false },
{ name: "Simone De Vivo", isCountry: false },
{ name: "Switzerland", isCountry: true },
{ name: "Blitz & Donner", isCountry: false },
{ name: "Cerca Research & Design Lab", isCountry: false },
{ name: "Reform GmbH", isCountry: false },
{ name: "Sarah Santacroce", isCountry: false },
{ name: "she explores tech", isCountry: false },
{ name: "Swiss Design Association", isCountry: false },
{ name: "Valerie Notter de Rabanal", isCountry: false },
{ name: "Thailand", isCountry: true },
{ name: "Tipaponr Tharawongthawat", isCountry: false },
{ name: "Turkey", isCountry: true },
{ name: "Bilal Akpinar", isCountry: false },
{ name: "Gaye Poçan", isCountry: false },
{ name: "United States", isCountry: true },
{ name: "2911 Creative LLC d/b/a Missionspring Studio", isCountry: false },
{ name: "76West", isCountry: false },
{ name: "Amanda Bauer", isCountry: false },
{ name: "Analogy", isCountry: false },
{ name: "Angeline Neo", isCountry: false },
{ name: "Autumn Dahlia Creative Services LLC", isCountry: false },
{ name: "Box Clever", isCountry: false },
{ name: "Brayan", isCountry: false },
{ name: "Business4Today.com", isCountry: false },
{ name: "Chameleon Studios", isCountry: false },
{ name: "Colibrily LLC", isCountry: false },
{ name: "Damn Good Humans", isCountry: false },
{ name: "Dayani", isCountry: false },
{ name: "Design Team at Omura", isCountry: false },
{ name: "Double Loop Marketing LLC", isCountry: false },
{ name: "Douglas Flandro", isCountry: false },
{ name: "Elliott Swigert", isCountry: false },
{ name: "Fabricio Teixeira", isCountry: false },
{ name: "Gooey.AI", isCountry: false },
{ name: "GROUP OF HUMANS", isCountry: false },
{ name: "Indiblu Creative", isCountry: false },
{ name: "James Junk", isCountry: false },
{ name: "Kailyn Nelson", isCountry: false },
{ name: "Kinship Creative", isCountry: false },
{ name: "Kristin keilt", isCountry: false },
{ name: "Lucy Crelli", isCountry: false },
{ name: "Lwindesign", isCountry: false },
{ name: "M.S.Architecture - Health and Design at NYIT Health and Design", isCountry: false },
{ name: "Matterall", isCountry: false },
{ name: "Mayra Cardoso do Nascimento", isCountry: false },
{ name: "Michael Weschler Productions", isCountry: false },
{ name: "Mike Simpson Design", isCountry: false },
{ name: "Mother’s Tongue", isCountry: false },
{ name: "Re-nourish", isCountry: false },
{ name: "Rkive Studio", isCountry: false },
{ name: "Sara Mckee", isCountry: false },
{ name: "shannon", isCountry: false },
{ name: "Social Workers Who Design", isCountry: false },
{ name: "SPACES", isCountry: false },
{ name: "Stefan Boublil", isCountry: false },
{ name: "STORM studio", isCountry: false },
{ name: "Studio SAKA", isCountry: false },
{ name: "Style & Entertaining", isCountry: false },
{ name: "Urna Bloom", isCountry: false },
{ name: "What if Design", isCountry: false },
{ name: "WHYWHATIF", isCountry: false },
{ name: "Uruguay", isCountry: true },
{ name: "Helen Hartley Consulting", isCountry: false },
{ name: "Lucia Delgado", isCountry: false },
{ name: "Upgrade", isCountry: false },
{ name: "Vietnam", isCountry: true },
{ name: "Dr Britta Boyer", isCountry: false },

];
